# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

boot = {
  initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  initrd.kernelModules = [ ];
  kernelModules = [ "kvm-intel" ];
  extraModulePackages = [ ];
  kernelPackages = pkgs.linuxPackages_latest;
  kernelParams = [ "acpi=force" ];
  extraModprobeConfig = '' options snd slots=snd-hda-intel '';
  };


  

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a0bd1025-d6d2-bb47-8567-f2ee4908fa3c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1A92-DBEB";
      fsType = "vfat";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
